CREATE TABLE IF NOT EXISTS {{DB}}.cart_events (`event_id` UUID DEFAULT generateUUIDv4(), `event_time` DateTime DEFAULT now(), `session_id` String, `user_id` UInt32, `product_sku` String, `product_name` String, `category` String, `action` Enum8('add' = 1, 'remove' = 2, 'update_qty' = 3), `quantity` UInt16, `unit_price` Decimal(10, 2), `country` String, `device` Enum8('desktop' = 1, 'mobile' = 2, 'tablet' = 3)) ENGINE = MergeTree() ORDER BY (event_time, session_id) SETTINGS index_granularity = 8192;

CREATE TABLE IF NOT EXISTS {{DB}}.checkout_events (`event_id` UUID DEFAULT generateUUIDv4(), `event_time` DateTime DEFAULT now(), `session_id` String, `user_id` UInt32, `event_type` Enum8('page_view' = 1, 'begin_checkout' = 2, 'add_payment' = 3, 'purchase' = 4, 'abandon' = 5), `cart_value` Decimal(10, 2), `items_count` UInt16, `country` String, `device` Enum8('desktop' = 1, 'mobile' = 2, 'tablet' = 3), `payment_method` String DEFAULT '') ENGINE = MergeTree() ORDER BY (event_time, session_id) SETTINGS index_granularity = 8192;

CREATE TABLE IF NOT EXISTS {{DB}}.customer_feedback (`feedback_id` UInt64, `customer_id` UInt32, `product_sku` LowCardinality(String), `product_name` LowCardinality(String), `category` LowCardinality(String), `rating` UInt8, `feedback_text_fts` String, `feedback_text_bloom` String, `feedback_text_plain` String, `created_at` DateTime, INDEX idx_feedback_fts feedback_text_fts TYPE text(tokenizer = 'splitByNonAlpha') GRANULARITY 100000000, INDEX idx_feedback_bloom feedback_text_bloom TYPE tokenbf_v1(10240, 3, 0) GRANULARITY 1) ENGINE = MergeTree() ORDER BY (category, product_sku, created_at) SETTINGS index_granularity = 8192;

CREATE TABLE IF NOT EXISTS {{DB}}.gold_customer_rfm (`customer_id` Int32, `customer_name` String, `customer_email` String, `customer_tier` String, `is_vip` Bool, `country` String, `total_orders` UInt64, `total_revenue` Decimal(38, 2), `avg_order_value` Decimal(38, 2), `first_order` DateTime64(6), `last_order` DateTime64(6), `recency_days` UInt32, `rfm_segment` String) ENGINE = MergeTree() ORDER BY (rfm_segment, customer_id) SETTINGS index_granularity = 8192;

CREATE TABLE IF NOT EXISTS {{DB}}.gold_daily_kpi (`dt` Date, `total_revenue` Decimal(38, 2), `total_orders` UInt64, `avg_order_value` Float64, `unique_customers` UInt64, `new_customers` UInt64, `vip_revenue` Decimal(38, 2), `failed_payments` UInt64, `payment_failure_rate` Float64, `top_category` String, `top_country` String) ENGINE = ReplacingMergeTree() ORDER BY dt SETTINGS index_granularity = 8192;

CREATE TABLE IF NOT EXISTS {{DB}}.gold_funnel_hourly (`dt` Date, `hour` UInt8, `country` String, `device` String, `page_views` UInt64, `cart_adds` UInt64, `checkouts` UInt64, `purchases` UInt64, `cart_rate` Float64, `checkout_rate` Float64, `purchase_rate` Float64) ENGINE = MergeTree() ORDER BY (dt, hour, country, device) SETTINGS index_granularity = 8192;

CREATE TABLE IF NOT EXISTS {{DB}}.gold_payment_health (`dt` Date, `payment_method` String, `provider` String, `status` String, `cnt` UInt64, `total_amount` Decimal(38, 2)) ENGINE = SummingMergeTree((cnt, total_amount)) ORDER BY (dt, payment_method, provider, status) SETTINGS index_granularity = 8192;

CREATE TABLE IF NOT EXISTS {{DB}}.gold_product_performance (`dt` Date, `product_sku` String, `product_name` String, `category` String, `orders` UInt64, `units_sold` UInt64, `revenue` Decimal(38, 2)) ENGINE = SummingMergeTree((orders, units_sold, revenue)) ORDER BY (dt, product_sku, category) SETTINGS index_granularity = 8192;

CREATE TABLE IF NOT EXISTS {{DB}}.gold_revenue_daily (`dt` Date, `country` String, `channel` String, `category` String, `orders` SimpleAggregateFunction(sum, UInt64), `revenue` SimpleAggregateFunction(sum, Decimal(38, 2)), `units_sold` SimpleAggregateFunction(sum, UInt64), `unique_customers` AggregateFunction(uniq, UInt32)) ENGINE = AggregatingMergeTree() ORDER BY (dt, country, channel, category) SETTINGS index_granularity = 8192;

CREATE TABLE IF NOT EXISTS {{DB}}.gold_vip_dashboard (`customer_id` Int32, `customer_name` String, `customer_email` String, `tier` String, `country` String, `total_orders` UInt64, `total_revenue` Decimal(38, 2), `failed_payments` UInt64, `last_order_at` DateTime64(6), `last_failure_reason` String, `risk_level` String) ENGINE = MergeTree() ORDER BY (risk_level, customer_id) SETTINGS index_granularity = 8192;

CREATE TABLE IF NOT EXISTS {{DB}}.inventory_events (`event_id` UUID DEFAULT generateUUIDv4(), `event_time` DateTime DEFAULT now(), `product_sku` String, `product_name` String, `category` String, `change_type` Enum8('restock' = 1, 'sale' = 2, 'adjustment' = 3, 'return' = 4), `quantity_change` Int32, `quantity_after` UInt32, `warehouse` String DEFAULT 'EU-Central') ENGINE = MergeTree() ORDER BY (event_time, product_sku) SETTINGS index_granularity = 8192;

CREATE TABLE IF NOT EXISTS {{DB}}.order_events (`event_id` UUID DEFAULT generateUUIDv4(), `event_time` DateTime DEFAULT now(), `order_id` UInt32, `customer_id` UInt32, `product_sku` String, `product_name` String, `category` String, `quantity` UInt16, `unit_price` Decimal(10, 2), `total_amount` Decimal(10, 2), `payment_method` String, `status` String, `country` String, `channel` String DEFAULT 'web', `device` String DEFAULT 'desktop') ENGINE = MergeTree() ORDER BY (event_time, order_id) SETTINGS index_granularity = 8192;

CREATE TABLE IF NOT EXISTS {{DB}}.page_events (`event_id` UUID DEFAULT generateUUIDv4(), `event_time` DateTime DEFAULT now(), `session_id` String, `user_id` UInt32, `page_url` String, `page_type` Enum8('home' = 1, 'category' = 2, 'product' = 3, 'cart' = 4, 'checkout' = 5, 'confirmation' = 6), `device` Enum8('desktop' = 1, 'mobile' = 2, 'tablet' = 3), `country` String, `referrer` String DEFAULT '') ENGINE = MergeTree() ORDER BY (event_time, session_id) SETTINGS index_granularity = 8192;

CREATE TABLE IF NOT EXISTS {{DB}}.payment_events (`event_id` UUID DEFAULT generateUUIDv4(), `event_time` DateTime DEFAULT now(), `order_id` UInt32, `user_id` UInt32, `amount` Decimal(10, 2), `currency` String DEFAULT 'EUR', `payment_method` String, `provider` String DEFAULT 'stripe', `status` Enum8('pending' = 1, 'success' = 2, 'failed' = 3, 'refunded' = 4), `failure_reason` String DEFAULT '', `country` String) ENGINE = MergeTree() ORDER BY (event_time, order_id) SETTINGS index_granularity = 8192;

CREATE TABLE IF NOT EXISTS {{DB}}.silver_customers (`id` Int32, `email` String, `full_name` String, `country` String, `tier` String, `is_vip` Bool, `created_at` DateTime64(6)) ENGINE = MergeTree() ORDER BY id SETTINGS index_granularity = 8192;

CREATE TABLE IF NOT EXISTS {{DB}}.silver_orders (`order_id` Int32, `customer_id` Int32, `customer_name` String, `customer_email` String, `customer_country` String, `customer_tier` String, `is_vip` Bool, `status` String, `total_amount` Decimal(10, 2), `payment_method` String, `country` String, `channel` String, `created_at` DateTime64(6), `items_count` UInt64, `items_revenue` Decimal(38, 2)) ENGINE = MergeTree() ORDER BY (order_id, created_at) SETTINGS index_granularity = 8192;

CREATE TABLE IF NOT EXISTS {{DB}}.silver_payments (`order_id` Int32, `payment_status` String, `provider` String, `failure_reason` String, `customer_id` Int32, `order_amount` Decimal(10, 2), `payment_method` String, `order_country` String, `order_channel` String, `order_status` String, `updated_at` DateTime64(6)) ENGINE = MergeTree() ORDER BY (order_id, updated_at) SETTINGS index_granularity = 8192;

CREATE TABLE IF NOT EXISTS {{DB}}.silver_products (`id` Int32, `sku` String, `name` String, `category` String, `price` Decimal(10, 2), `inventory_available` Int32, `created_at` DateTime64(6)) ENGINE = MergeTree() ORDER BY id SETTINGS index_granularity = 8192;

CREATE TABLE IF NOT EXISTS {{DB}}.user_activity (`event_time` DateTime DEFAULT now(), `user_email` String, `user_name` String, `event_type` Enum8('login' = 1, 'page_view' = 2, 'persona_switch' = 3, 'logout' = 4), `page_path` String DEFAULT '', `persona` String DEFAULT '', `user_agent` String DEFAULT '', `session_id` String DEFAULT '') ENGINE = MergeTree() ORDER BY (event_time, user_email) TTL event_time + toIntervalDay(90) SETTINGS index_granularity = 8192;
