import NextAuth from "next-auth";
import Credentials from "next-auth/providers/credentials";

// Accounts: the local admin (ADMIN_EMAIL) and the 5 personas, all using the
// password generated by install.sh (DEMO_PASSWORD, stored in a k8s Secret).
// ALLOWED_EMAIL_DOMAIN optionally opens sign-in to any address of one domain
// with the same password; empty means only the accounts above can sign in.
const DEMO_DOMAIN = (process.env.DEMO_EMAIL_DOMAIN || "clickshop.io").toLowerCase();
const PERSONAS = ["ceo", "sales", "data", "sre", "ai-engineer"];

function adminEmail(): string {
  return (process.env.ADMIN_EMAIL || `admin@${DEMO_DOMAIN}`).toLowerCase().trim();
}

function isKnownAccount(email: string): boolean {
  if (email === adminEmail()) return true;
  if (PERSONAS.some((p) => email === `${p}@${DEMO_DOMAIN}`)) return true;
  const domain = (process.env.ALLOWED_EMAIL_DOMAIN || "").toLowerCase().trim().replace(/^@/, "");
  return !!domain && email.endsWith(`@${domain}`);
}

function timingSafeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

export const { handlers, auth, signIn, signOut } = NextAuth({
  basePath: "/api/sso",
  trustHost: true,
  providers: [
    Credentials({
      credentials: {
        email: { label: "Email", type: "email" },
        password: { label: "Password", type: "password" },
      },
      authorize(credentials) {
        const email = (credentials?.email as string)?.toLowerCase().trim();
        const password = (credentials?.password as string) ?? "";
        const expected = process.env.DEMO_PASSWORD ?? "";
        if (!email || !expected || !timingSafeEqual(password, expected)) return null;
        if (!isKnownAccount(email)) return null;
        const name = email
          .split("@")[0]
          .split(/[.\-_]/)
          .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
          .join(" ");
        return { id: email, email, name };
      },
    }),
  ],
  pages: { signIn: "/auth/signin" },
  session: { strategy: "jwt" },
  callbacks: {
    jwt({ token, user }) {
      if (user) {
        token.email = user.email;
        token.name = user.name;
        token.isAdmin = user.email === adminEmail();
      }
      return token;
    },
    session({ session, token }) {
      if (session.user) {
        session.user.email = token.email ?? "";
        session.user.name = token.name ?? "";
        (session.user as { isAdmin?: boolean }).isAdmin = token.isAdmin === true;
      }
      return session;
    },
  },
});
